# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../try_except_retry_loop.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../try_except_retry_loop.py
"""

import os as _os
_MSG_ROOT = _os.getenv("ASYA_MSG_ROOT", "/proc/asya/msg")


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_retry_pipeline(payload: dict) -> dict:
    """Entrypoint for flow 'retry_pipeline'"""
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    p = payload
    p['attempt'] = 0

    _next.append(resolve("prepare_request"))
    _next.append(resolve("router_retry_pipeline_line_12_while_0"))
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return p

def router_retry_pipeline_line_14_try_enter_0(payload: dict) -> dict:
    """Try-enter router: sets _on_error header and inserts try body"""
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    _os.makedirs(f"{_MSG_ROOT}/headers", exist_ok=True)
    with open(f"{_MSG_ROOT}/headers/_on_error", "w") as _f:
        _f.write(resolve("router_retry_pipeline_line_14_except_dispatch_0"))

    _next.append(resolve("call_external_api"))
    _next.append(resolve("call_another_api"))
    _next.append(resolve("router_retry_pipeline_line_14_try_exit_0"))

    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def router_retry_pipeline_line_14_try_exit_0(payload: dict) -> dict:
    """Try-exit router: clears _on_error header (success path)"""
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    import os as _os_try_exit
    _on_error_path = f"{_MSG_ROOT}/headers/_on_error"
    if _os_try_exit.path.exists(_on_error_path):
        _os_try_exit.remove(_on_error_path)


    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def router_retry_pipeline_line_14_except_dispatch_0(payload: dict) -> dict:
    """Except-dispatch router: matches error type and routes to handler"""
    p = payload
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    with open(f"{_MSG_ROOT}/status/error/type") as _f:
        _error_type = _f.read().strip()
    with open(f"{_MSG_ROOT}/status/error/mro") as _f:
        _error_mro = _f.read().splitlines()
    _all_types = [_error_type] + _error_mro

    if "ConnectionError" in _all_types:
        import shutil as _shutil_exc; _shutil_exc.rmtree(f"{_MSG_ROOT}/status/error", ignore_errors=True)
        _next.append(resolve("log_retry"))
    elif "ValueError" in _all_types:
        import shutil as _shutil_exc; _shutil_exc.rmtree(f"{_MSG_ROOT}/status/error", ignore_errors=True)
        pass
    else:
        _next.append(resolve("router_retry_pipeline_line_14_reraise_0"))

    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def router_retry_pipeline_line_14_reraise_0(payload: dict) -> dict:
    """Reraise router: raises RuntimeError for unhandled exceptions"""
    with open(f"{_MSG_ROOT}/status/error/type") as _f:
        _error_type = _f.read().strip() or 'unknown'
    with open(f"{_MSG_ROOT}/status/error/message") as _f:
        _error_msg = _f.read().strip() or 'unknown error'
    raise RuntimeError(f"Unhandled exception {_error_type}: {_error_msg}")

def router_retry_pipeline_line_13_seq(payload: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = payload
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    p['attempt'] += 1
    _next.append(resolve("router_retry_pipeline_line_14_try_enter_0"))

    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def router_retry_pipeline_line_12_while_0(payload: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = payload
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    if p['attempt'] < 3:
        _next.append(resolve("router_retry_pipeline_line_13_seq"))
        _next.append(resolve("router_retry_pipeline_line_12_while_0"))
    else:
        pass

    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def end_retry_pipeline(payload: dict) -> dict:
    """Exitpoint for flow 'retry_pipeline'"""
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("")
    return payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
