# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../fanout_conditional.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../fanout_conditional.py
"""

import copy


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_adaptive_flow(payload: dict):
    """Entrypoint for flow 'adaptive_flow'"""
    _next = []
    _next.append(resolve("classifier"))
    _next.append(resolve("router_adaptive_flow_line_12_if"))
    yield "SET", ".route.next[:0]", _next
    yield payload

async def fanout_adaptive_flow_line_13(payload: dict):
    """Fan-out router: dispatches to sub-agents and aggregator (line 13)"""
    p = payload

    origin_id = yield "GET", ".id"
    _next_tail = yield "GET", ".route.next"

    _agg = resolve("fanin_adaptive_flow_line_13")

    _slices = []
    _slices.append((resolve("fast_analyzer"), p['text']))
    _slices.append((resolve("deep_analyzer"), p['text']))

    _n = len(_slices) + 1
    _fan_in = {
        "actor": _agg,
        "origin_id": origin_id,
        "slice_count": _n,
        "aggregation_key": "/results",
    }

    # Index 0: parent payload forwarded to aggregator
    yield "SET", ".route.next", [_agg, resolve("formatter")] + _next_tail
    yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": 0}
    yield copy.deepcopy(p)

    for _i, (_actor, _payload) in enumerate(_slices):
        yield "SET", ".route.next", [_actor, _agg]
        yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": _i + 1}
        yield _payload

async def router_adaptive_flow_line_12_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['parallel']:
        _next.append(resolve("fanout_adaptive_flow_line_13"))
    else:
        _next.append(resolve("sequential_analyzer"))
        _next.append(resolve("formatter"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def end_adaptive_flow(payload: dict):
    """Exitpoint for flow 'adaptive_flow'"""
    yield "SET", ".route.next", []
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
