apiVersion: v1
kind: Service
metadata:
  name: {{ include "asya-injector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    {{- include "asya-injector.selectorLabels" . | nindent 4 }}
