apiVersion: v2
name: asya-gateway
description: Asya MCP Gateway with PostgreSQL backend
type: application
# versions are replaced by automatically .github/workflows/release.yml
version: 0.0.0
appVersion: "0.0.0"
