apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: test-doubler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-actors.labels" . | nindent 4 }}
spec:
  actor: test-doubler
  transport: {{ .Values.transport }}
  {{- include "asya-test-actors.pubsub-spec" . | nindent 2 }}
  overlays:
  - asya-test-actor

  scaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    pollingInterval: 5
    cooldownPeriod: 30
    queueLength: 5

  workload:
    kind: Deployment
    template:
      spec:
        containers:
        - name: asya-runtime
          image: {{ .Values.workload.image }}
          imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
          env:
          - name: ASYA_HANDLER
            value: asya_testing.handlers.payload.pipeline_doubler
          - name: ASYA_INCLUDE_ROUTE_INFO
            value: 'true'
