apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: test-large-payload
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-actors.labels" . | nindent 4 }}
spec:
  actor: test-large-payload
  transport: {{ .Values.transport }}
  {{- include "asya-test-actors.pubsub-spec" . | nindent 2 }}
  flavors:
  - asya-test-actor

  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 5
    cooldownPeriod: 30
    queueLength: 5

  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.handlers.payload.large_payload_handler
