apiVersion: v2
name: asya-actor
description: Generic Helm chart for deploying AsyncActor resources with health validation
type: application
# versions are replaced by automatically .github/workflows/release.yml
version: 0.0.0
appVersion: "0.0.0"
keywords:
- asya
- actor
- async
- kubernetes
maintainers:
- name: Asya Team
