{{- $sink := index .Values "x-sink" }}
{{- if $sink.enabled }}
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: {{ $sink.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-crew.x-sink.labels" . | nindent 4 }}
  {{- with $sink.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  actor: {{ $sink.name }}
  compositionSelector:
    matchLabels:
      asya.sh/transport: {{ $sink.transport }}
  transport: {{ $sink.transport }}
  {{- include "asya-crew.pubsub-spec" . | nindent 2 }}
  {{- if .Values.persistence.enabled }}
  stateProxy:
    {{- include "asya-crew.persistence.stateProxy" . | nindent 4 }}
  {{- end }}

  {{- with $sink.sidecar }}
  sidecar:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if $sink.scaling.enabled }}
  scaling:
    {{- toYaml $sink.scaling | nindent 4 }}
  {{- end }}

  image: {{ include "asya-crew.x-sink.image" . }}
  imagePullPolicy: {{ include "asya-crew.x-sink.imagePullPolicy" . }}
  handler: asya_crew.sink.sink_handler
  {{- $envList := list }}
  {{- range $key, $value := $sink.env }}
  {{- if ne $value "" }}
  {{- $envList = append $envList (dict "name" $key "value" $value) }}
  {{- end }}
  {{- end }}
  {{- if $envList }}
  env:
    {{- toYaml $envList | nindent 4 }}
  {{- end }}
  {{- with $sink.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
