{{- $sump := index .Values "x-sump" }}
{{- if $sump.enabled }}
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: {{ $sump.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-crew.x-sump.labels" . | nindent 4 }}
  {{- with $sump.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  actor: {{ $sump.name }}
  compositionSelector:
    matchLabels:
      asya.sh/transport: {{ $sump.transport }}
  transport: {{ $sump.transport }}
  {{- include "asya-crew.pubsub-spec" . | nindent 2 }}
  {{- if .Values.persistence.enabled }}
  stateProxy:
    {{- include "asya-crew.persistence.stateProxy" (dict "Values" .Values "bucket" .Values.persistence.config.errorsBucket) | nindent 4 }}
  {{- end }}

  {{- with $sump.sidecar }}
  sidecar:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if $sump.scaling.enabled }}
  scaling:
    {{- toYaml $sump.scaling | nindent 4 }}
  {{- end }}

  image: {{ include "asya-crew.x-sump.image" . }}
  imagePullPolicy: {{ include "asya-crew.x-sump.imagePullPolicy" . }}
  handler: asya_crew.sump.sump_handler
  {{- $envList := list }}
  {{- range $key, $value := $sump.env }}
  {{- if ne $value "" }}
  {{- $envList = append $envList (dict "name" $key "value" $value) }}
  {{- end }}
  {{- end }}
  {{- if $envList }}
  env:
    {{- toYaml $envList | nindent 4 }}
  {{- end }}
  {{- with $sump.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
