# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../try_except_finally.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../try_except_finally.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_resource_pipeline(payload: dict):
    """Entrypoint for flow 'resource_pipeline'"""
    _next = []
    p = payload
    p['status'] = 'started'
    _next.append(resolve("router_resource_pipeline_line_3_try_enter_0"))
    yield "SET", ".route.next[:0]", _next
    yield p

async def router_resource_pipeline_line_7_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['status'] = 'failed'
    _next.append(resolve("handle_failure"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_resource_pipeline_line_3_try_enter_0(payload: dict):
    """Try-enter router: sets _on_error header and inserts try body"""
    _next = []
    yield "SET", ".headers._on_error", resolve("router_resource_pipeline_line_3_except_dispatch_0")
    _next.append(resolve("acquire_resource"))
    _next.append(resolve("process_with_resource"))
    _next.append(resolve("router_resource_pipeline_line_3_try_exit_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_resource_pipeline_line_3_try_exit_0(payload: dict):
    """Try-exit router: clears _on_error header (success path)"""
    _next = []
    headers = yield "GET", ".headers"
    if "_on_error" in headers:
        yield "DEL", ".headers._on_error"
    _next.append(resolve("release_resource"))
    _next.append(resolve("finalize"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_resource_pipeline_line_3_except_dispatch_0(payload: dict):
    """Except-dispatch router: matches error type and routes to handler"""
    p = payload
    _next = []
    _error_type = yield "GET", ".status.error.type"
    _error_mro = yield "GET", ".status.error.mro"
    _all_types = [_error_type] + _error_mro

    if "RuntimeError" in _all_types:
        yield "DEL", ".status.error"
        _next.append(resolve("router_resource_pipeline_line_7_seq"))
    else:
        _next.append(resolve("router_resource_pipeline_line_3_reraise_0"))
    _next.append(resolve("release_resource"))
    _next.append(resolve("finalize"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_resource_pipeline_line_3_reraise_0(payload: dict):
    """Reraise router: raises RuntimeError for unhandled exceptions"""
    _error_type = yield "GET", ".status.error.type"
    _error_msg = yield "GET", ".status.error.message"
    raise RuntimeError(f"Unhandled exception {_error_type}: {_error_msg}")

async def end_resource_pipeline(payload: dict):
    """Exitpoint for flow 'resource_pipeline'"""
    yield "SET", ".route.next", []
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
