auth:
  rootUser: minioadmin
  rootPassword: minioadmin

service:
  type: NodePort
  nodePort: 30900

buckets:
- name: asya-results
- name: asya-errors

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: false
  size: 10Gi
