# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../hierarchical_delegation.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../hierarchical_delegation.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_hierarchical_delegation(payload: dict):
    """Entrypoint for flow 'hierarchical_delegation'"""
    _next = []
    _next.append(resolve("root_agent"))
    _next.append(resolve("router_hierarchical_delegation_line_57_if"))
    yield "SET", ".route.next[:0]", _next
    yield payload

def router_hierarchical_delegation_line_63_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('subtask') == 'api':
        _next.append(resolve("api_specialist"))
        _next.append(resolve("final_assembler"))
    else:
        _next.append(resolve("data_generalist"))
        _next.append(resolve("final_assembler"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_hierarchical_delegation_line_61_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('subtask') == 'sql':
        _next.append(resolve("sql_specialist"))
        _next.append(resolve("final_assembler"))
    else:
        _next.append(resolve("router_hierarchical_delegation_line_63_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_hierarchical_delegation_line_74_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('subtask') == 'edit':
        _next.append(resolve("editor"))
        _next.append(resolve("final_assembler"))
    else:
        _next.append(resolve("content_generalist"))
        _next.append(resolve("final_assembler"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_hierarchical_delegation_line_72_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('subtask') == 'write':
        _next.append(resolve("writer"))
        _next.append(resolve("final_assembler"))
    else:
        _next.append(resolve("router_hierarchical_delegation_line_74_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_hierarchical_delegation_line_68_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('domain') == 'content':
        _next.append(resolve("content_team_lead"))
        _next.append(resolve("router_hierarchical_delegation_line_72_if"))
    else:
        _next.append(resolve("generalist"))
        _next.append(resolve("final_assembler"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_hierarchical_delegation_line_57_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('domain') == 'data':
        _next.append(resolve("data_team_lead"))
        _next.append(resolve("router_hierarchical_delegation_line_61_if"))
    else:
        _next.append(resolve("router_hierarchical_delegation_line_68_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def end_hierarchical_delegation(payload: dict):
    """Exitpoint for flow 'hierarchical_delegation'"""
    yield "SET", ".route.next", []
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
