{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: localstack-sqs
  namespace: {{ .Release.Namespace }}
  labels:
    app: sqs
    app.kubernetes.io/name: localstack-sqs
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - port: 4566
    targetPort: 4566
    protocol: TCP
    name: edge
    {{- if and .Values.service.nodePort (eq (.Values.service.type | default "ClusterIP") "NodePort") }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: sqs
{{- end }}
