"""Generate Python code for routers."""

from __future__ import annotations

import os
from pathlib import Path
from textwrap import dedent

from asya_cli.flow.grouper import Router


class CodeGenerator:
    def __init__(self, flow_name: str, routers: list[Router], source_file: str, output_file: str | None = None):
        self.flow_name = flow_name
        self.routers = routers

        # Compute relative path from output to source if both are provided
        if output_file:
            try:
                output_path = Path(output_file).resolve()
                source_path = Path(source_file).resolve()
                # Get relative path from output directory to source file
                relative_path = os.path.relpath(source_path, output_path.parent)
                self.source_file = relative_path
            except (ValueError, OSError):
                # Fallback to basename if relative path computation fails
                self.source_file = os.path.basename(source_file)
        else:
            self.source_file = os.path.basename(source_file)

        self.all_handlers: set[str] = set()

    def generate(self) -> str:
        self._collect_handlers()

        parts = []
        parts.append(self._generate_header())
        if self._has_loop_guards():
            parts.append(self._generate_max_iter_constant())
        parts.append(self._generate_routers())
        parts.append(self._generate_resolve_function())

        return "\n".join(parts)

    def _has_loop_guards(self) -> bool:
        return any(r.guard_max_iter is not None for r in self.routers)

    def _generate_max_iter_constant(self) -> str:
        default = next(r.guard_max_iter for r in self.routers if r.guard_max_iter is not None)
        return dedent(f'''\
            import os as _os
            _ASYA_MAX_LOOP_ITERATIONS = int(_os.environ.get("ASYA_MAX_LOOP_ITERATIONS", "{default}"))
            ''')

    def _collect_handlers(self) -> None:
        for router in self.routers:
            self.all_handlers.add(router.name)
            for actor_name in router.true_branch_actors:
                self.all_handlers.add(actor_name)
            for actor_name in router.false_branch_actors:
                self.all_handlers.add(actor_name)

    def _generate_header(self) -> str:
        return dedent(f'''\
            # fmt: off
            # ruff: noqa
            """
            Auto-generated by asya flow compiler
            Source: {self.source_file}

            DO NOT EDIT THIS FILE MANUALLY
            Regenerate by running: asya flow compile {self.source_file}
            """
            ''')

    def _generate_routers(self) -> str:
        lines = []
        lines.append("\n# " + "=" * 70)
        lines.append("# Generated Routers (for kubernetes deployment)")
        lines.append("# " + "=" * 70)
        lines.append("")

        for router in self.routers:
            if router.name.startswith("start_"):
                lines.append(self._generate_start_router(router))
            elif router.name.startswith("end_"):
                lines.append(self._generate_end_router(router))
            elif router.is_loop_back:
                lines.append(self._generate_loop_back_router(router))
            else:
                lines.append(self._generate_router(router))

        return "\n".join(lines)

    def _generate_start_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(message: dict) -> dict:")
        lines.append(f'    """Entrypoint for flow \'{self.flow_name}\'"""')
        lines.append("    r = message['route']")
        lines.append("    c = r['current']")
        lines.append("")

        if router.true_branch_actors:
            filtered_actors = [name for name in router.true_branch_actors if not name.startswith("end_")]
            if filtered_actors:
                next_list = ", ".join([f'resolve("{name}")' for name in filtered_actors])
                lines.append(f"    r['actors'][c+1:c+1] = [{next_list}]")
        lines.append("    r['current'] = c + 1")
        lines.append("    return message")
        lines.append("")

        return "\n".join(lines)

    def _generate_end_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(message: dict) -> dict:")
        lines.append(f'    """Exitpoint for flow \'{self.flow_name}\'"""')
        lines.append("    return message")
        lines.append("")

        return "\n".join(lines)

    def _generate_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(message: dict) -> dict:")
        lines.append('    """Router for control flow and payload mutations"""')
        lines.append("    p = message['payload']")
        lines.append("    r = message['route']")
        lines.append("    c = r['current']")
        lines.append("    _next = []")
        lines.append("")

        for mutation in router.mutations:
            lines.append(f"    {mutation.code}")

        if router.condition:
            lines.append(f"    if {router.condition.test}:")
            if router.true_branch_actors:
                filtered_true = [actor for actor in router.true_branch_actors if not actor.startswith("end_")]
                for actor in filtered_true:
                    lines.append(f'        _next.append(resolve("{actor}"))')
                if not filtered_true:
                    lines.append("        pass")
            else:
                lines.append("        pass")
            lines.append("    else:")
            if router.false_branch_actors:
                filtered_false = [actor for actor in router.false_branch_actors if not actor.startswith("end_")]
                for actor in filtered_false:
                    lines.append(f'        _next.append(resolve("{actor}"))')
                if not filtered_false:
                    lines.append("        pass")
            else:
                lines.append("        pass")
        else:
            filtered_actors = [actor for actor in router.true_branch_actors if not actor.startswith("end_")]
            for actor in filtered_actors:
                lines.append(f'    _next.append(resolve("{actor}"))')

        lines.append("")
        lines.append("    r['actors'][c+1:c+1] = _next")
        lines.append("    r['current'] = c + 1")
        lines.append("    return message")
        lines.append("")

        return "\n".join(lines)

    def _generate_loop_back_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(message: dict) -> dict:")
        if router.guard_max_iter is not None:
            lines.append('    """Loop-back router: re-inserts loop actors into route (guarded)"""')
        else:
            lines.append('    """Loop-back router: re-inserts loop actors into route"""')
        lines.append("    p = message['payload']")
        lines.append("    r = message['route']")
        lines.append("    c = r['current']")
        lines.append("    _next = []")
        lines.append("")

        for mutation in router.mutations:
            lines.append(f"    {mutation.code}")

        if router.guard_max_iter is not None:
            lines.append(f'    _self = resolve("{router.name}")')
            lines.append("    if r['actors'][:c].count(_self) >= _ASYA_MAX_LOOP_ITERATIONS:")
            lines.append(
                f'        raise RuntimeError(f"Max loop iterations ({{_ASYA_MAX_LOOP_ITERATIONS}}) exceeded for while-loop at line {router.lineno}")'
            )
            lines.append("")

        filtered_actors = [actor for actor in router.true_branch_actors if not actor.startswith("end_")]
        for actor in filtered_actors:
            lines.append(f'    _next.append(resolve("{actor}"))')

        lines.append("")
        lines.append("    r['actors'][c+1:c+1] = _next")
        lines.append("    r['current'] = c + 1")
        lines.append("    return message")
        lines.append("")

        return "\n".join(lines)

    def _generate_resolve_function(self) -> str:
        return dedent('''
            # ======================================================================
            # Handler Resolution
            # ======================================================================

            import os
            import logging

            _HANDLER_TO_ACTOR: dict[str, str] = {}
            _SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

            for _env_var, _handler_name in os.environ.items():
                if _env_var.startswith('ASYA_HANDLER_'):
                    _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
                    _HANDLER_TO_ACTOR[_handler_name] = _actor_name

                    # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
                    _parts = _handler_name.split('.')
                    for _i in range(len(_parts)):
                        _suffix = '.'.join(_parts[_i:])
                        if _suffix not in _SUFFIX_TO_HANDLERS:
                            _SUFFIX_TO_HANDLERS[_suffix] = []
                        _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

            logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


            def resolve(handler_full_name: str) -> str:
                """
                Resolve handler name to actor name using suffix-based matching.

                Looks up handler in environment variables:
                - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

                Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
                - "method" (shortest)
                - "ClassName.method" (class + method)
                - "module.ClassName.method" (partial path)
                - "full.module.path.ClassName.method" (full path)

                Args:
                    handler_full_name: Any suffix of the full handler path

                Returns:
                    Actor name for routing (kebab-case, lowercase)

                Raises:
                    ValueError: If handler suffix not found or is ambiguous

                Examples:
                    # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

                    # All of these work (if unambiguous):
                    resolve("clean")  # shortest suffix
                    resolve("DataPreprocessor.clean")  # class + method
                    resolve("class_instantiation.DataPreprocessor.clean")  # full path

                    # Ambiguous suffix
                    # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
                    resolve("clean")  # raises ValueError: ambiguous, use longer suffix
                """
                if handler_full_name in _SUFFIX_TO_HANDLERS:
                    candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
                    if len(candidates) == 1:
                        return _HANDLER_TO_ACTOR[candidates[0]]
                    else:
                        raise ValueError(
                            f"Handler suffix '{handler_full_name}' is ambiguous. "
                            f"Found multiple matches: {candidates}. "
                            f"Use a longer suffix to disambiguate."
                        )

                raise ValueError(
                    f"Handler '{handler_full_name}' not found in environment variables. "
                    f'No handler ends with suffix "{handler_full_name}". '
                    f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
                )
            ''')
