# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../while_react_loop.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../while_react_loop.py
"""

import os as _os
_ASYA_MAX_LOOP_ITERATIONS = int(_os.environ.get("ASYA_MAX_LOOP_ITERATIONS", "100"))


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_react_agent(message: dict) -> dict:
    """Entrypoint for flow 'react_agent'"""
    r = message['route']

    r['next'] = [resolve("router_react_agent_line_10_loop_back_0")] + r['next']
    return message

def router_react_agent_line_12_if(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    if p.get('tool_calls'):
        _next.append(resolve("execute_tool"))
    else:
        pass

    r['next'] = _next + r['next']
    return message

def router_react_agent_line_10_loop_back_0(message: dict) -> dict:
    """Loop-back router: re-inserts loop actors into route (guarded)"""
    p = message['payload']
    r = message['route']
    _next = []

    _self = resolve("router_react_agent_line_10_loop_back_0")
    if r['prev'].count(_self) >= _ASYA_MAX_LOOP_ITERATIONS:
        raise RuntimeError(f"Max loop iterations ({_ASYA_MAX_LOOP_ITERATIONS}) exceeded for while-loop at line 10")

    _next.append(resolve("llm_call"))
    _next.append(resolve("router_react_agent_line_12_if"))
    _next.append(resolve("router_react_agent_line_10_loop_back_0"))

    r['next'] = _next + r['next']
    return message

def end_react_agent(message: dict) -> dict:
    """Exitpoint for flow 'react_agent'"""
    return message


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
