enabled: true
region: us-east-1

service:
  type: NodePort
  nodePort: 30566

auth:
  accessKey: test
  secretKey: test

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
