# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../adk_llm_auditor.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../adk_llm_auditor.py
"""

import os as _os
_ASYA_MAX_LOOP_ITERATIONS = int(_os.environ.get("ASYA_MAX_LOOP_ITERATIONS", "100"))

import copy


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_llm_auditor(payload: dict):
    """Entrypoint for flow 'llm_auditor'"""
    _next = []
    p = payload
    p['iteration'] = 0
    p['status'] = 'started'
    p['partial'] = True
    _next.append(resolve("extract_claims"))
    _next.append(resolve("router_llm_auditor_line_37_if"))
    yield "SET", ".route.next[:0]", _next
    yield p

async def router_llm_auditor_line_38_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['status'] = 'no_claims'

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_86_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['partial'] = False
    _next.append(resolve("finalize"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_62_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['prev_score'] = p['aggregate_score']
    _next.append(resolve("router_llm_auditor_line_42_loop_back_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_67_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['status'] = 'approved'

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_69_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['aggregate_score'] >= 70:
        _next.append(resolve("critique"))
        _next.append(resolve("reviser"))
        _next.append(resolve("router_llm_auditor_line_79_if"))
    else:
        _next.append(resolve("critique"))
        _next.append(resolve("deep_reviser"))
        _next.append(resolve("router_llm_auditor_line_79_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_80_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['status'] = 'max_iterations'
    _next.append(resolve("router_llm_auditor_line_86_seq"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_83_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['prev_score'] = p['aggregate_score']

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_79_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['iteration'] >= p.get('max_iterations', 5):
        _next.append(resolve("router_llm_auditor_line_80_seq"))
    else:
        _next.append(resolve("router_llm_auditor_line_83_seq"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_66_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['aggregate_score'] >= 90:
        _next.append(resolve("router_llm_auditor_line_67_seq"))
    else:
        _next.append(resolve("router_llm_auditor_line_69_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_61_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['aggregate_score'] > p.get('prev_score', 0) and p['aggregate_score'] < 70:
        _next.append(resolve("router_llm_auditor_line_62_seq"))
    else:
        _next.append(resolve("router_llm_auditor_line_66_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def fanout_llm_auditor_line_52(payload: dict):
    """Fan-out router: dispatches to sub-agents and aggregator (line 52)"""
    p = payload

    origin_id = yield "GET", ".id"
    _next_tail = yield "GET", ".route.next"

    _agg = resolve("fanin_llm_auditor_line_52")

    _slices = []
    _slices.append((resolve("accuracy_scorer"), p['response']))
    _slices.append((resolve("completeness_scorer"), p['response']))

    _n = len(_slices) + 1
    _fan_in = {
        "actor": _agg,
        "origin_id": origin_id,
        "slice_count": _n,
        "aggregation_key": "/scores",
    }

    # Index 0: parent payload forwarded to aggregator
    yield "SET", ".route.next", [_agg, resolve("adk_llm_auditor.QualityScorer.aggregate"), resolve("router_llm_auditor_line_61_if")] + _next_tail
    yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": 0}
    yield copy.deepcopy(p)

    for _i, (_actor, _payload) in enumerate(_slices):
        yield "SET", ".route.next", [_actor, _agg]
        yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": _i + 1}
        yield _payload

async def router_llm_auditor_line_46_try_enter_0(payload: dict):
    """Try-enter router: sets _on_error header and inserts try body"""
    _next = []
    yield "SET", ".headers._on_error", resolve("router_llm_auditor_line_46_except_dispatch_0")
    _next.append(resolve("llm_generate"))
    _next.append(resolve("router_llm_auditor_line_46_try_exit_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_46_try_exit_0(payload: dict):
    """Try-exit router: clears _on_error header (success path)"""
    _next = []
    headers = yield "GET", ".headers"
    if "_on_error" in headers:
        yield "DEL", ".headers._on_error"
    _next.append(resolve("fanout_llm_auditor_line_52"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_46_except_dispatch_0(payload: dict):
    """Except-dispatch router: matches error type and routes to handler"""
    p = payload
    _next = []
    _error_type = yield "GET", ".status.error.type"
    _error_mro = yield "GET", ".status.error.mro"
    _all_types = [_error_type] + _error_mro

    if True:
        yield "DEL", ".status.error"
        _next.append(resolve("fallback_generate"))
    _next.append(resolve("fanout_llm_auditor_line_52"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_43_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['iteration'] += 1
    _next.append(resolve("router_llm_auditor_line_46_try_enter_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_42_loop_back_0(payload: dict):
    """Loop-back router: re-inserts loop actors into route (guarded)"""
    p = payload
    _next = []
    _self = resolve("router_llm_auditor_line_42_loop_back_0")
    _prev = yield "GET", ".route.prev"
    if _prev.count(_self) >= _ASYA_MAX_LOOP_ITERATIONS:
        raise RuntimeError(f"Max loop iterations ({_ASYA_MAX_LOOP_ITERATIONS}) exceeded for while-loop at line 42")

    _next.append(resolve("router_llm_auditor_line_43_seq"))
    _next.append(resolve("router_llm_auditor_line_42_loop_back_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_llm_auditor_line_37_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if not p.get('claims'):
        _next.append(resolve("router_llm_auditor_line_38_seq"))
    else:
        _next.append(resolve("router_llm_auditor_line_42_loop_back_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def end_llm_auditor(payload: dict):
    """Exitpoint for flow 'llm_auditor'"""
    yield "SET", ".route.next", []
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
