{{- if and .Values.sampleGatewayDb.postgresql.enabled .Values.sampleGatewayDb.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-asya-gateway-postgresql-data
  namespace: {{ include "asya-playground.namespace.infra" . }}
  labels:
    app: {{ .Release.Name }}-postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-16"
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sampleGatewayDb.postgresql.persistence.size }}
{{- end }}
