{{- if .Values.sampleGatewayDb.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-asya-gateway-postgresql
  namespace: {{ include "asya-playground.namespace.infra" . }}
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: {{ .Values.sampleGatewayDb.postgresql.auth.password | quote }}
{{- end }}
