{{- if .Values.sampleGatewayDb.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-asya-gateway-postgresql
  namespace: {{ include "asya-playground.namespace.infra" . }}
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/resource-policy": keep
spec:
  type: {{ .Values.sampleGatewayDb.postgresql.service.type }}
  ports:
  - port: {{ .Values.sampleGatewayDb.postgresql.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Release.Name }}-postgresql
{{- end }}
