{{- if and .Values.sampleTransport.sqsLocalstack.enabled (eq .Values.global.transport "sqs") }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: localstack-sqs
    app.kubernetes.io/name: aws-creds
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sample-transport
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.sampleTransport.sqsLocalstack.auth.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.sampleTransport.sqsLocalstack.auth.secretAccessKey | quote }}
{{- end }}
