# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../try_except_simple.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../try_except_simple.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_order_processing(message: dict) -> dict:
    """Entrypoint for flow 'order_processing'"""
    r = message['route']

    r['next'] = [resolve("router_order_processing_line_2_try_enter_0")] + r['next']
    return message

def router_order_processing_line_5_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['status'] = 'invalid'
    _next.append(resolve("notify_rejection"))

    r['next'] = _next + r['next']
    return message

def router_order_processing_line_2_try_enter_0(message: dict) -> dict:
    """Try-enter router: sets _on_error header and inserts try body"""
    r = message['route']
    _next = []

    message.setdefault('headers', {})
    message['headers']['_on_error'] = resolve("router_order_processing_line_2_except_dispatch_0")

    _next.append(resolve("validate_order"))
    _next.append(resolve("router_order_processing_line_2_try_exit_0"))

    r['next'] = _next + r['next']
    return message

def router_order_processing_line_2_try_exit_0(message: dict) -> dict:
    """Try-exit router: clears _on_error header (success path)"""
    r = message['route']
    _next = []

    message.get('headers', {}).pop('_on_error', None)


    r['next'] = _next + r['next']
    return message

def router_order_processing_line_2_except_dispatch_0(message: dict) -> dict:
    """Except-dispatch router: matches error type and routes to handler"""
    p = message['payload']
    r = message['route']
    _next = []

    _error = message.get('status', {}).get('error', {})
    _error_type = _error.get('type', '')
    _error_mro = _error.get('mro', [])
    _all_types = [_error_type] + _error_mro

    if "ValueError" in _all_types:
        message.get('status', {}).pop('error', None)
        _next.append(resolve("router_order_processing_line_5_seq"))
    else:
        _next.append(resolve("router_order_processing_line_2_reraise_0"))

    r['next'] = _next + r['next']
    return message

def router_order_processing_line_2_reraise_0(message: dict) -> dict:
    """Reraise router: raises RuntimeError for unhandled exceptions"""
    _error = message.get('status', {}).get('error', {})
    _error_type = _error.get('type', 'unknown')
    _error_msg = _error.get('message', 'unknown error')
    raise RuntimeError(f"Unhandled exception {_error_type}: {_error_msg}")

def end_order_processing(message: dict) -> dict:
    """Exitpoint for flow 'order_processing'"""
    return message


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
