# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../flow.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../flow.py
"""

import os as _os
_MSG_ROOT = _os.getenv("ASYA_MSG_ROOT", "/proc/asya/msg")

import json as _json


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_research_flow(payload: dict) -> dict:
    """Entrypoint for flow 'research_flow'"""
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    _next.append(resolve("fanout_research_flow_line_2"))
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def fanout_research_flow_line_2(payload: dict):
    """Fan-out router: dispatches to sub-agents and aggregator (line 2)"""
    p = payload

    with open(f"{_MSG_ROOT}/id") as _f:
        origin_id = _f.read().strip()
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()

    _agg = resolve("fanin_research_flow_line_2")

    # Accumulate (actor_name, slice_payload) pairs
    _slices = []
    for t in p['topics']:
        _slices.append((resolve("research_agent"), t))

    _n = len(_slices) + 1
    _fan_in = {
        "actor": _agg,
        "origin_id": origin_id,
        "slice_count": _n,
        "aggregation_key": "/results",
    }

    # Index 0: parent payload forwarded to aggregator via VFS route
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join([_agg, resolve("summarizer")] + _next_tail))
    _os.makedirs(f"{_MSG_ROOT}/headers", exist_ok=True)
    with open(f"{_MSG_ROOT}/headers/x-asya-fan-in", "w") as _f:
        _f.write(_json.dumps({**_fan_in, "slice_index": 0}))
    yield _json.loads(_json.dumps(p))

    # Indices 1..N: sub-agent slices
    for _i, (_actor, _payload) in enumerate(_slices):
        with open(f"{_MSG_ROOT}/route/next", "w") as _f:
            _f.write("\n".join([_actor, _agg]))
        with open(f"{_MSG_ROOT}/headers/x-asya-fan-in", "w") as _f:
            _f.write(_json.dumps({**_fan_in, "slice_index": _i + 1}))
        yield _payload

def end_research_flow(payload: dict) -> dict:
    """Exitpoint for flow 'research_flow'"""
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("")
    return payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
