# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../flow.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../flow.py
"""

import os as _os
_MSG_ROOT = _os.getenv("ASYA_MSG_ROOT", "/proc/asya/msg")

import json as _json
import os as _fanout_os

_FANIN_SHARDS = int(_fanout_os.environ.get("ASYA_FANIN_SHARDS", "1"))

if _FANIN_SHARDS > 1:
    import xxhash as _xxhash

    def _resolve_aggregator(origin_id, target):
        best = max(
            range(_FANIN_SHARDS),
            key=lambda i: _xxhash.xxh64_intdigest(f"{origin_id}:{i}".encode()),
        )
        shard = f"{target}-{best}"
        return shard, {"x-asya-route-override": {target: shard}}
else:
    def _resolve_aggregator(origin_id, target):
        return target, {}



# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_research_flow(payload: dict) -> dict:
    """Entrypoint for flow 'research_flow'"""
    with open(f"{_MSG_ROOT}/route/next") as _f:
        _next_tail = _f.read().splitlines()
    _next = []

    _next.append(resolve("fanout_research_flow_L2"))
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("\n".join(_next + _next_tail))
    return payload

def fanout_research_flow_L2(message: dict):
    """Fan-out router: dispatches to sub-agents and aggregator (line 2)"""
    p = message['payload']
    r = message['route']
    origin_id = message['id']
    _hdrs = message.get('headers', {})

    _agg_abstract = resolve("summarizer")
    _agg, _override = _resolve_aggregator(origin_id, _agg_abstract)

    # Accumulate (actor_name, slice_payload) pairs
    _slices = []
    for t in p['topics']:
        _slices.append((resolve("research_agent"), t))

    _n = len(_slices) + 1
    _fan_in = {
        "actor": _agg_abstract,
        "origin_id": origin_id,
        "slice_count": _n,
        "aggregation_key": "/results",
    }

    # Index 0: parent payload forwarded to aggregator (route manually shifted)
    yield {
        'id': origin_id,
        'route': {
            'prev': r['prev'] + [r['curr']],
            'curr': _agg,
            'next': [] + r['next'],
        },
        'headers': {**_hdrs, **_override, 'x-asya-fan-in': {**_fan_in, 'slice_index': 0}},
        'payload': _json.loads(_json.dumps(p)),
    }

    # Indices 1..N: sub-agent slices
    import uuid as _uuid
    for _i, (_actor, _payload) in enumerate(_slices):
        yield {
            'id': str(_uuid.uuid4()),
            'parent_id': origin_id,
            'route': {'prev': [], 'curr': _actor, 'next': [_agg]},
            'headers': {**_hdrs, **_override, 'x-asya-fan-in': {**_fan_in, 'slice_index': _i + 1}},
            'payload': _payload,
        }

def end_research_flow(payload: dict) -> dict:
    """Exitpoint for flow 'research_flow'"""
    with open(f"{_MSG_ROOT}/route/next", "w") as _f:
        _f.write("")
    return payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
