# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../orchestrator_workers.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../orchestrator_workers.py
"""

import os as _os
_ASYA_MAX_LOOP_ITERATIONS = int(_os.environ.get("ASYA_MAX_LOOP_ITERATIONS", "100"))


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_orchestrator_workers(payload: dict):
    """Entrypoint for flow 'orchestrator_workers'"""
    _next = []
    p = payload
    p['iteration'] = 0
    p['worker_results'] = []
    _next.append(resolve("router_orchestrator_workers_line_53_loop_back_0"))
    yield "SET", ".route.next[:0]", _next
    yield p

def router_orchestrator_workers_line_67_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('next_action') == 'write':
        _next.append(resolve("writing_worker"))
        _next.append(resolve("router_orchestrator_workers_line_70_if"))
    else:
        _next.append(resolve("router_orchestrator_workers_line_70_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_orchestrator_workers_line_65_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('next_action') == 'analyze':
        _next.append(resolve("analysis_worker"))
        _next.append(resolve("router_orchestrator_workers_line_70_if"))
    else:
        _next.append(resolve("router_orchestrator_workers_line_67_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_orchestrator_workers_line_70_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['iteration'] >= 10:
        _next.append(resolve("synthesizer"))
    else:
        pass

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_orchestrator_workers_line_63_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('next_action') == 'research':
        _next.append(resolve("data_worker"))
        _next.append(resolve("router_orchestrator_workers_line_70_if"))
    else:
        _next.append(resolve("router_orchestrator_workers_line_65_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_orchestrator_workers_line_59_if(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('is_complete'):
        _next.append(resolve("synthesizer"))
    else:
        _next.append(resolve("router_orchestrator_workers_line_63_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_orchestrator_workers_line_54_seq(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['iteration'] += 1
    _next.append(resolve("orchestrator"))
    _next.append(resolve("router_orchestrator_workers_line_59_if"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def router_orchestrator_workers_line_53_loop_back_0(payload: dict):
    """Loop-back router: re-inserts loop actors into route (guarded)"""
    p = payload
    _next = []
    _self = resolve("router_orchestrator_workers_line_53_loop_back_0")
    _prev = yield "GET", ".route.prev"
    if _prev.count(_self) >= _ASYA_MAX_LOOP_ITERATIONS:
        raise RuntimeError(f"Max loop iterations ({_ASYA_MAX_LOOP_ITERATIONS}) exceeded for while-loop at line 53")

    _next.append(resolve("router_orchestrator_workers_line_54_seq"))
    _next.append(resolve("router_orchestrator_workers_line_53_loop_back_0"))

    yield "SET", ".route.next[:0]", _next
    yield payload

def end_orchestrator_workers(payload: dict):
    """Exitpoint for flow 'orchestrator_workers'"""
    yield "SET", ".route.next", []
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
