#!/usr/bin/env python3
"""
CLI for Flow DSL compiler.

Commands:
    compile    - Compile flow to routers
    validate   - Validate flow without compiling

Usage:
    asya flow compile <flow_file.py> [options]
    asya flow validate <flow_file.py> [options]
"""

import argparse
import sys
from pathlib import Path

from asya_cli.flow import FlowCompileError, FlowCompiler


def cmd_compile(args):
    """Compile flow file."""
    try:
        if not args.output_dir:
            print("[-] Error: --output-dir is required", file=sys.stderr)
            sys.exit(1)

        compiler = FlowCompiler(
            verbose=args.verbose,
        )

        compiled_file = compiler.compile_file(args.flow_file, args.output_dir, overwrite=args.overwrite)
        print(f"[+] Successfully compiled flow to: {compiled_file}")

        if args.plot:
            try:
                dot_file, png_path = compiler.generate_plot(args.output_dir, plot_width=args.plot_width)
                print(f"[+] Generated graphviz dot file: {dot_file}")
                if png_path:
                    print(f"[+] Generated graphviz png plot: {png_path}")
            except ImportError as e:
                print(f"[!] Warning: {e}", file=sys.stderr)
            except RuntimeError as e:
                print(f"[!] Warning: {e}", file=sys.stderr)
            except Exception as e:
                print(f"[!] Warning: Failed to generate plot: {e}", file=sys.stderr)

        warnings = compiler.get_warnings()
        if warnings:
            print("\nWarnings:", file=sys.stderr)
            for warning in warnings:
                print(f"\n{warning}", file=sys.stderr)

    except FlowCompileError as e:
        print("[-] Compilation failed:\n", file=sys.stderr)
        print(str(e), file=sys.stderr)
        sys.exit(1)
    except (FileNotFoundError, ValueError) as e:
        print(f"[-] {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"[-] Unexpected error: {e}", file=sys.stderr)
        if args.verbose:
            import traceback

            traceback.print_exc()
        sys.exit(1)


def cmd_validate(args):
    """Validate flow file."""
    try:
        compiler = FlowCompiler(
            verbose=args.verbose,
        )

        source_path = Path(args.flow_file)
        if not source_path.exists():
            print(f"[-] Source file not found: {args.flow_file}", file=sys.stderr)
            sys.exit(1)

        source_code = source_path.read_text()
        compiler.validate(source_code, str(source_path))

        print(f"[+] Flow is valid: {args.flow_file}")

        # Show warnings if any
        warnings = compiler.get_warnings()
        if warnings:
            print("\nWarnings:", file=sys.stderr)
            for warning in warnings:
                print(f"\n{warning}", file=sys.stderr)

    except FlowCompileError as e:
        print("[-] Validation failed:\n", file=sys.stderr)
        print(str(e), file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"[-] Unexpected error: {e}", file=sys.stderr)
        if args.verbose:
            import traceback

            traceback.print_exc()
        sys.exit(1)


def cmd_init(args):
    """Generate template flow file."""
    template = '''"""
Flow template generated by asya-cli.

Define your flow function below following the Flow DSL constraints:
- Function signature: def flow_name(p: dict) -> dict
- Handler calls: p = handler(p)
- Payload mutations: p["key"] = value
- Control flow: if/elif/else, while
- Loop control: break, continue
- Return: return p
"""

# Import your handlers
# from my_module import preprocessor, handler_a, handler_b


def FLOW_NAME(p: dict) -> dict:
    """
    Your flow description here.

    Args:
        p: Payload dictionary

    Returns:
        Processed payload
    """
    # Example flow logic:
    # p = preprocessor(p)
    # if p["type"] == "A":
    #     p = handler_a(p)
    # else:
    #     p = handler_b(p)
    # return p

    return p
'''

    flow_name = args.flow_name
    output_file = args.output or f"{flow_name}.py"

    output_path = Path(output_file)
    if output_path.exists() and not args.force:
        print(f"[-] File already exists: {output_file}", file=sys.stderr)
        print("    Use --overwrite to overwrite", file=sys.stderr)
        sys.exit(1)

    # Replace placeholder with actual flow name
    template = template.replace("FLOW_NAME", flow_name)

    output_path.write_text(template)
    print(f"[+] Created flow template: {output_file}")


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="asya flow",
        description="Flow DSL compiler for Asya",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    subparsers = parser.add_subparsers(dest="command", required=True, help="Command to run")

    # Compile command
    compile_parser = subparsers.add_parser("compile", help="Compile flow to routers")
    compile_parser.add_argument("flow_file", help="Flow source file (.py)")
    compile_parser.add_argument(
        "--output-dir",
        "-o",
        required=True,
        help="Output directory for compiled files (must not exist or be empty)",
    )
    compile_parser.add_argument(
        "--disable-infinite-loop-check",
        action="store_true",
        help="Disable infinite loop detection",
    )
    compile_parser.add_argument("--verbose", "-v", action="store_true", help="Show verbose output")
    compile_parser.add_argument(
        "--plot",
        action="store_true",
        help="Generate flow diagram in DOT format and PNG (requires graphviz for PNG)",
    )
    compile_parser.add_argument(
        "--plot-width",
        type=int,
        default=50,
        help="Maximum width for plot node labels (default: 50 characters)",
    )
    compile_parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files in output directory",
    )
    compile_parser.set_defaults(func=cmd_compile)

    # Validate command
    validate_parser = subparsers.add_parser("validate", help="Validate flow without compiling")
    validate_parser.add_argument("flow_file", help="Flow source file (.py)")
    validate_parser.add_argument(
        "--disable-infinite-loop-check",
        action="store_true",
        help="Disable infinite loop detection",
    )
    validate_parser.add_argument("--verbose", "-v", action="store_true", help="Show verbose output")
    validate_parser.set_defaults(func=cmd_validate)

    # Init command
    init_parser = subparsers.add_parser("init", help="Generate template flow file")
    init_parser.add_argument("flow_name", help="Flow function name")
    init_parser.add_argument("--output", "-o", help="Output file (default: <flow_name>.py)")
    init_parser.add_argument("--overwrite", action="store_true", help="Overwrite existing files")
    init_parser.set_defaults(func=cmd_init)

    args = parser.parse_args(argv)

    # Run command
    args.func(args)


if __name__ == "__main__":
    main()
