# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../flow.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../flow.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_test_nested_flow(message: dict) -> dict:
    """Entrypoint for flow 'test_nested_flow'"""
    r = message['route']

    r['next'] = [resolve("validate_input"), resolve("router_test_nested_flow_line_4_if")] + r['next']
    return message

def router_test_nested_flow_line_7_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['route'] = 'A-X'
    _next.append(resolve("route_a_x"))
    _next.append(resolve("finalize_result"))

    r['next'] = _next + r['next']
    return message

def router_test_nested_flow_line_10_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['route'] = 'A-Y'
    _next.append(resolve("route_a_y"))
    _next.append(resolve("finalize_result"))

    r['next'] = _next + r['next']
    return message

def router_test_nested_flow_line_6_if(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['path'] = 'A'
    if p['level2'] == 'X':
        _next.append(resolve("router_test_nested_flow_line_7_seq"))
    else:
        _next.append(resolve("router_test_nested_flow_line_10_seq"))

    r['next'] = _next + r['next']
    return message

def router_test_nested_flow_line_15_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['route'] = 'B-X'
    _next.append(resolve("route_b_x"))
    _next.append(resolve("finalize_result"))

    r['next'] = _next + r['next']
    return message

def router_test_nested_flow_line_18_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['route'] = 'B-Y'
    _next.append(resolve("route_b_y"))
    _next.append(resolve("finalize_result"))

    r['next'] = _next + r['next']
    return message

def router_test_nested_flow_line_14_if(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['path'] = 'B'
    if p['level2'] == 'X':
        _next.append(resolve("router_test_nested_flow_line_15_seq"))
    else:
        _next.append(resolve("router_test_nested_flow_line_18_seq"))

    r['next'] = _next + r['next']
    return message

def router_test_nested_flow_line_4_if(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    if p['level1'] == 'A':
        _next.append(resolve("router_test_nested_flow_line_6_if"))
    else:
        _next.append(resolve("router_test_nested_flow_line_14_if"))

    r['next'] = _next + r['next']
    return message

def end_test_nested_flow(message: dict) -> dict:
    """Exitpoint for flow 'test_nested_flow'"""
    return message


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
