# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../while_loop_processing.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../while_loop_processing.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_loop_flow(message: dict) -> dict:
    """Entrypoint for flow 'loop_flow'"""
    r = message['route']

    r['next'] = [resolve("initialize"), resolve("router_loop_flow_line_12_while_0")] + r['next']
    return message

def router_loop_flow_line_19_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['abort'] = 2
    _next.append(resolve("router_loop_flow_line_12_loop_back_0"))

    r['next'] = _next + r['next']
    return message

def router_loop_flow_line_17_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['abort'] = 1
    _next.append(resolve("process_abort"))
    _next.append(resolve("router_loop_flow_line_19_seq"))

    r['next'] = _next + r['next']
    return message

def router_loop_flow_line_23_if(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    if p['threshold_met']:
        _next.append(resolve("finalize_loop"))
    else:
        pass

    r['next'] = _next + r['next']
    return message

def router_loop_flow_line_16_if(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    if p.get('skip_threshold_check'):
        _next.append(resolve("router_loop_flow_line_17_seq"))
    else:
        _next.append(resolve("check_threshold"))
        _next.append(resolve("router_loop_flow_line_23_if"))

    r['next'] = _next + r['next']
    return message

def router_loop_flow_line_13_seq(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['iteration'] += 1
    _next.append(resolve("process_item"))
    _next.append(resolve("router_loop_flow_line_16_if"))

    r['next'] = _next + r['next']
    return message

def router_loop_flow_line_12_loop_back_0(message: dict) -> dict:
    """Loop-back router: re-inserts loop actors into route"""
    p = message['payload']
    r = message['route']
    _next = []

    _next.append(resolve("router_loop_flow_line_12_while_0"))

    r['next'] = _next + r['next']
    return message

def router_loop_flow_line_12_while_0(message: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = message['payload']
    r = message['route']
    _next = []

    p['iteration'] = 0
    if p['iteration'] < p['max_iterations']:
        _next.append(resolve("router_loop_flow_line_13_seq"))
        _next.append(resolve("router_loop_flow_line_12_loop_back_0"))
    else:
        _next.append(resolve("finalize_loop"))

    r['next'] = _next + r['next']
    return message

def end_loop_flow(message: dict) -> dict:
    """Exitpoint for flow 'loop_flow'"""
    return message


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
