# LocalStack configuration for E2E testing
awsProviderConfig:
  name: localstack
  credentialsSource: Secret
  secretRef:
    namespace: crossplane-system
    name: aws-creds
    key: credentials
  endpoint:
    enabled: true
    url: http://localstack.localstack.svc.cluster.local:4566
    hostnameImmutable: true
  skipCredentialsValidation: true
  skipMetadataApiCheck: true
  skipRequestingAccountId: true
  skipRegionValidation: true
  s3UsePathStyle: true

awsRegion: us-east-1
