{{- if .Values.sampleMonitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: asya-actors
  namespace: {{ include "asya-playground.namespace.monitoring" . }}
  labels:
    app.kubernetes.io/name: asya-actors
    app.kubernetes.io/part-of: asya
spec:
  selector:
    matchExpressions:
    - key: asya.sh/actor
      operator: Exists
    - key: asya.sh/metrics
      operator: NotIn
      values: ["false"]
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    path: /metrics
{{- end }}
