enabled: true
region: us-east-1

service:
  type: NodePort
  nodePort: 30567

auth:
  accessKey: test
  secretKey: test

buckets: []

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
