{{- if and .Values.sampleTransport.rabbitmq.enabled (eq .Values.global.transport "rabbitmq") }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ include "asya-playground.namespace.infra" . }}
  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.sampleTransport.rabbitmq.service.type }}
  ports:
  - port: {{ .Values.sampleTransport.rabbitmq.service.amqpPort }}
    targetPort: amqp
    protocol: TCP
    name: amqp
  - port: {{ .Values.sampleTransport.rabbitmq.service.managementPort }}
    targetPort: management
    protocol: TCP
    name: management
  selector:
    app: rabbitmq
{{- end }}
