{{- if and .Values.sampleStorage.minio.enabled (eq .Values.global.storage "minio") }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ include "asya-playground.namespace.infra" . }}
  labels:
    app: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  rootPassword: {{ .Values.sampleStorage.minio.auth.rootPassword | quote }}
  rootUser: {{ .Values.sampleStorage.minio.auth.rootUser | quote }}
{{- end }}
