# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../single_actor.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../single_actor.py
"""


# ======================================================================
# Single-Actor Flow: no router needed
# The actor below IS the entrypoint; label it in your AsyncActor spec:
#   asya.sh/flow: single_actor_flow
#   asya.sh/flow-role: entrypoint
# ======================================================================

FLOW_METADATA = {
    "flow_name": "single_actor_flow",
    "type": "single-actor",
    "actor": 'document_processor',
    "labels": {
        "asya.sh/flow": "single_actor_flow",
        "asya.sh/flow-role": "entrypoint",
    },
}
